-- Bảng lưu link stream m3u8 do admin tự nhập
-- media_id: TMDB id của phim/series
-- type: 'movie' hoặc 'tv'
-- season/episode: 0 nếu là movie, số thật nếu là TV
create table public.streams (
  id bigint generated by default as identity primary key,
  media_id integer not null,
  type text not null check (type in ('movie', 'tv')),
  season integer not null default 0,
  episode integer not null default 0,
  m3u8_url text not null,
  label text, -- tuỳ chọn: "Vietsub", "Thuyết minh", "1080p"...
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (media_id, type, season, episode)
);

-- Auto-update updated_at (tái sử dụng function từ 03_histories.sql)
create trigger set_updated_at
before update on public.streams
for each row
execute function public.set_updated_at();

-- Index để query nhanh theo media_id + type
create index streams_media_idx
on public.streams (media_id, type, season, episode);

-- Row Level Security
alter table public.streams enable row level security;

-- Ai cũng có thể đọc (để player load được)
create policy "Anyone can view streams"
on public.streams
for select
to anon, authenticated
using (true);

-- Chỉ service_role (admin) mới được insert/update/delete
-- Khi gọi từ admin page, dùng supabaseAdmin client với service key
create policy "Only service role can insert streams"
on public.streams
for insert
to service_role
with check (true);

create policy "Only service role can update streams"
on public.streams
for update
to service_role
using (true)
with check (true);

create policy "Only service role can delete streams"
on public.streams
for delete
to service_role
using (true);
